### ISSUE TITLE
Script and guide to check if DSF connected correctly

### ISSUE THREAD

**Issue by juliangruendner** [medizininformatik-initiative/feasibility-dsf-process#23]
A script with a guide should be added, which allows a site to check if a feasibility query has been answered successfully.

The script should be executable on the same VM as the DSF installation and us the client credentials to  download the respective

task, measure and measure report resources so that a user can verify them.

**Comment by DiCanio** [comment]
Will not be implemented since there is already a plugin for this very purpose:
https://github.com/highmed/highmed-processes/wiki/Process-Ping-Description-v0.7.0
